# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  dockerId: qilinchen@auo.com                  # 阿里云 login username
  namespace: auocq                              # 阿里云 命名空间
  imageName: auosys                        # 阿里云 仓库名称
  registry: registry.cn-shanghai.aliyuncs.com/auocq/auosys   # 阿里云 公网地址
  dockerfilepath:  WebNotebook/Dockerfile       # Github Dockerfile相对路径


steps:
- task: CmdLine@2
  inputs:
    script: |
      echo ready to execute command
      ls
      sed -i 's/{Writable}/$(Writable)/g' WebNotebook/appsettings.Production.json
      sed -i 's/{ReadOnly}/$(ReadOnly)/g' WebNotebook/appsettings.Production.json
      echo command executed
- script: |
    docker build -f $(dockerfilepath) -t $(imageName) .
    docker login -u $(dockerId) -p $(pwd) $(registry)
    docker tag $(imageName) $(registry)/$(namespace)/$(imageName)
    docker push $(registry)/$(namespace)/$(imageName)
  displayName: push to aliyun